### PR TITLE
Added support for the AXP2101

### PR DESCRIPTION
**Pull request by KevinBeckers**
Moved the AXP192 and AXP2101 to separate files. Tested on a M5stack Core3

### CODE REVIEW

**Comment by rcloran** [comment]
Hi! Thank you for your PR. Unfortunately I don't have time to properly get back into Rust on ESP at the moment.

I have a minor concern with this, which is that it is essentially a duplication of all of the (already overly verbose) code. I haven't thought about this very deeply, so please excuse any dumb questions I have, but, have you thought about whether there's a way to unify the code in any way? If that's not practical, do you think this would be better served as a separate project, since it targets some separate hardware?

You could help me by reviewing the other open PR ( #5  ), and I'll ask @doraneko94 to review this one, and I'd be happy to merge this based on that review if you've also looked at the other one.

**Comment by KevinBeckers** [comment]
Hi, no problem! I will take a look at @doraneko94 PR. 
As for the axp2101, I agree with you on that there can be a lot of refactoring, so let me try to unify the code.

**Comment by rcloran** [comment]
I've spent a little more time looking at this and some of the other AXP crates around. I'm still on the fence whether this should be its own crate or supported here. It'd be kinda nice to have a central place for the related AXP devices, and it seems like there is quite a lot of code that could end up being shared. I can also imagine some sort of macro language for describing flags and registers that would make writing drivers for new devices much easier and more succinct.

I've been thinking along those sorts of lines for how to create an async version of the axp192 driver, and this is something I'm hoping to dive into over the next few weeks... So perhaps adding disparate AXP devices wouldn't be so crazy if I'm going to create these macros.

Have you got anywhere with trying to refactor? I don't want to duplicate any work you've done, and would love to hear ideas for achieving the goal (ideally of how to implement both other devices, and async implementations :)) better than what I've described above.

**Comment by rcloran** [comment]
Urgh, I'm remembering now why I never got any further with the macro thought. It does not seem like there's a feasible way of doing it.

**Comment by hyx0329** [comment]
Sorry to interrupt here, but I've written [a driver for AXP2101](https://github.com/hyx0329/axp2101-rs) some time ago. Does that fit the need? I'm sure there do exist a lot to improve.

**Comment by rcloran** [comment]
Thanks, @hyx0329 ! I think the most reasonable course of action is to recommend your project instead of this one. What do you think, @KevinBeckers ?

Any reason not too publish on crates.io? Might make your project easier to discover and use.

**Pull request closed without merging**
